### ISSUE TITLE
Scripto_Adapter_Exception The provided adapter method “getPageTranscriptionStatus” does not exist.

### ISSUE THREAD

**Issue by ValeryCC** [omeka/plugin-Scripto#30]
This issue was reported back in 2.3 and butler had fixed this in 2.3.2 (found in this repo: https://github.com/ui-libraries/plugin-Scripto) in March 2019.

We recently had to upgrade from 2.3.2 to 2.4 due to the login issue (which 2.4 did fix...thank you!).

However, that broke the individual transcription item pages. It was the same _exact_ issue we ran into here: https://forum.omeka.org/t/scribe-theme-install/6978

We see the same exact error message with 2.4:
```
Omeka has encountered an error
Scripto_Adapter_Exception
The provided adapter method “getPageTranscriptionStatus” does not exist.

Scripto_Adapter_Exception: The provided adapter method “getPageTranscriptionStatus” does not exist. in /home/xxx/public_html/omeka/plugins/Scripto/libraries/Scripto.php:106
```

I compared 2.3.2 and 2.4 and the fix in 2.3.2 is not present in 2.4. Perhaps having 2 separate repos led to neglecting changes in the other? Should these repos be combined so there's one authority.

In a similar vein, the link to the Scripto github bug report found here https://scripto.org/, does not point to any Scripto github repo. Instead it points to https://github.com/omeka/Omeka/issues.

**Comment by jimsafley** [comment]
I'm not sure what I can do from here. The ui-libraries fork should pull in our new changes, or, if there's a bug fix, they should submit a pull request.

**Comment by ValeryCC** [comment]
Apologies! I had no idea we were working with a fork. Thank you for explaining the options forward.
